database:
    address: "mongodb://localhost:27017"
    database: "Messenger"
    messages: "Messages"
    users: "Users"
    chats: "Chats"
    files: "Files"
    chat_settings: "Chat_settings"
    chats_array: "Chats_array"
    personal_settings: "Personal_settings"
web:
    port: "8384"