database:
    address: "mongodb+srv://alexMessengerAdmin:alex_password@alexmessenger.0tqg5.mongodb.net/test?authSource=admin&replicaSet=atlas-cdqgma-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true"
    database: "AlexMessenger"
    messages: "Messages"
    users: "Users"
    chats: "Chats"
    files: "Files"
web:
    port: "8384"